server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.133.193:3306/monitor_data_analysis?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT%2b8
    username: root
    password: Bdilab@1308
    druid:
      max-wait: 60000
      max-active: 10
      min-idle: 1

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    cache-enabled: false